### PR TITLE
refactor: Split constants into networks and tokens

### PR DESCRIPTION
**Pull request by pxrl**
In advance of importing additional chain information from UMA.

### CODE REVIEW

**Comment by pxrl** [comment]
nb. This can wait to go in until after the Espresso work has wrapped up.

**Review by james-a-morris — COMMENTED** [review]
Will circle back after the rebase but LGTM

**Comment by pxrl** [comment]
@james-a-morris I've merged in the latest master, so this should be good to go now :+1:

**Review by nicholaspai — APPROVED** [review]

**Review by james-a-morris — APPROVED** [review]
LGTM!

**Pull request merged**
